#set page(numbering: "1", number-align: right)
#set list(marker: ("#", "-"))
#set enum(numbering: "1.a.")

#align(center)[
  #set par(leading: 1em, spacing: 1.2em)
  #text(size: 1.5em, weight: "bold", "SLR Parsing Table")\
  #text(
    size: 1.2em,
    weight: "semibold",
    datetime(day: 9, month: 4, year: 2026).display("[day] [month repr:long], [year]"),
  )
]
#line(length: 100%)
#v(2em)

== Construction of SLR parsing table
#line()
*Input:* An augmented grammar $G'$.\
*Output:* The SLR parsing table functions $"ACTION"$ and $"GOTO"$ for $G'$.

*Method:*
+ Construct $C = {I_0, I_1, I_2, ..., I_n}$, the collection of sets of LR(0) items for $G'$.
+ State $i$ is constructed from $I_i$. The parsing actions for state $i$ are determined as follows:
  + If [$A -> alpha dot a beta$] is in $I_i$ and $"GOTO"[I_i, a] = I_j$, then set $"ACTION"[i, a]$ to "$"Shift" j$". Here, $a$ must be a terminal.
  + If [$A -> alpha dot$] is in $I_i$, then set $"ACTION"[i, a]$ to "$"Reduce" A -> alpha$" for all  in $a$ in $"FOLLOW"(A)$.
  + If [$S' -> S dot$] is in $I_i$, then set $"ACTION"[i, \$]$ to $"ACCEPT"$.
  If any conflicting actions are generated by the above rules, we say that the grammar is SLR(1), in which case the algorithms fails to produce a parser.
+ The $"GOTO"$ transitions for state $i$ is constructed for all non-terminals $A$ using the rule:\
  If $"GOTO"[I_i, A] = I_j$, then $"GOTO"[i, A] = j$.
+ All entries not defined by rules 2 and 3 are made $"ERROR"$.
+ The initial state of the parser is the one constructed from the set of items containing [$S' -> dot S$].
